name: Build & Deploy (one-step)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate index.html
        run: python generate_index.py

      - name: Prepare site directory
        run: |
          mkdir site
          cp -r output/index.html site/
          cp -r uploads site/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: ''

      - name: Show URL
        run: echo "Deployed to ${{ steps.deployment.outputs.page_url }}"
